### PR TITLE
Fix build on Qt 6.6.0

### LINKED ISSUE #1611: Failure to build and run on Qt 6.6.0
### Operating System

Linux

### Version of PolyMC

PolyMC 5.1 (polymc-bin), polymc-git

### Version of Qt

Qt 6.6.0

### Description of bug

When building PolyMC from git, the following errors occur:

```
/home/swurl/.cache/yay/polymc-git/src/PolyMC/launcher/translations/TranslationsModel.cpp: In member function ‘Language* TranslationsModel::findLanguage(const QString&)’:
/home/swurl/.cache/yay/polymc-git/src/PolyMC/launcher/translations/TranslationsModel.cpp:503:16: error: cannot convert ‘QList::iterator’ to ‘Language*’ in return
503 | return found;
| ^~~~~
| |
| QList::iterator
/home/swurl/.cache/yay/polymc-git/src/PolyMC/launcher/translations/TranslationsModel.cpp: In member function ‘QModelIndex TranslationsModel::selectedIndex()’:
/home/swurl/.cache/yay/polymc-git/src/PolyMC/launcher/translations/TranslationsModel.cpp:634:28: error: no match for ‘operator-’ (operand types are ‘Language*’ and ‘QList::iterator’)
634 | return index(found - d->m_languages.begin(), 0, QModelIndex());
| ~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~
| | |
| Language* QList::iterator
```

Attempting to use `polymc-bin` and running it results in:

```
warning: direct reference to protected function _ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex' in /usr/lib/libQt6Widgets.so.6' may break pointer equality
polymc: _ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex: /usr/lib/libQt6Widgets.so.6: error due to GNU_PROPERTY_1_NEEDED_INDIRECT_EXTERN_ACCESS
```

### Steps to reproduce

* Install Qt 6.6.0
* Attempt to build polymc-git
* Attempt to run polymc-bin

### Suspected cause

Breaking changes within Qt 6.6

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by ghost**
Closes #1611

### CODE REVIEW

**Review by Sneedplex — APPROVED** [review]

**Comment by Sneedplex** [comment]
LGTM.
