### ISSUE TITLE
Wayland requires JVM flags to work in Minecraft instance

### ISSUE THREAD

**Issue by outusuke** [PolyMC/PolyMC#1771]
### Operating System

Linux

### Version of PolyMC

polymc 7.1

### Version of Qt

qt 6.11.1

### Description of bug

Wayland doesn’t work out of the box in the Minecraft instance. It needs extra JVM arguments to use Wayland correctly.

Workaround: add
-DMC_DEBUG_ENABLED -DMC_DEBUG_PREFER_WAYLAND

### Steps to reproduce

Run on Wayland only (no XWayland) and start the Minecraft instance without the JVM args `-DMC_DEBUG_ENABLED -DMC_DEBUG_PREFER_WAYLAND`; Wayland doesn’t work properly.

java.lang.IllegalStateException: Failed to initialize GLFW, errors: [GLFW 0x1000E] X11: The DISPLAY environment variable is missing
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:61)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:161)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:481)
	at net.minecraft.client.main.Main.main(Main.java:278)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:61)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:161)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:481)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:278)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Kaydax** [comment]
Which minecraft version? Also any mod loaders installed?

**Comment by outusuke** [comment]
26.2 vanilla

**Comment by Kaydax** [comment]
> 26.2 vanilla

What DE / Distro and GPU? I tested on hyprland + Nvidia on cachyos and was unable to reproduce

**Comment by outusuke** [comment]
Wayland works on Minecraft `1.21.11` without any extra JVM flags. In the `26.x` versions, it seems to require `-DMC_DEBUG_ENABLED -DMC_DEBUG_PREFER_WAYLAND`. This looks like it was introduced in `26.x`, and it appears to be fixed in `26-3-snapshot-4`, where Linux now prefers Wayland natively when available.

fedora gnome hd graphics 2000

**Comment by outusuke** [comment]
I tested using the AppImage version because the Flatpak Minecraft snapshot instance `26-3-snapshot-4` throws this error:


`[10:08:56] [main/WARN]: Failed to get system info for SDL Platform
java.lang.NoClassDefFoundError: org/lwjgl/sdl/SDLPlatform
	at com.mojang.blaze3d.platform.Window.getPlatform(Window.java:126)
	at net.minecraft.SystemReport.setDetail(SystemReport.java:96)
	at net.minecraft.client.Minecraft.fillSystemReport(Minecraft.java:2570)
	at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2522)
	at net.minecraft.client.main.Main.main(Main.java:147)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.sdl.SDLPlatform
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 12 more
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.
Time: 2026-07-24 10:08:56
Description: Loading library SDL
java.lang.NoClassDefFoundError: org/lwjgl/sdl/SDL
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadSdl(NativeLibrariesBootstrap.java:284)
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201)
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105)
	at net.minecraft.client.main.Main.main(Main.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.sdl.SDL
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 11 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: main
Stacktrace:
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadSdl(NativeLibrariesBootstrap.java:284)
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201)
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105)
-- Library directory contents --
Details:
	Contents of java.library.path : <not a directory>
	Contents of org.lwjgl.librarypath: 
		libfreetype.so: unknown type
		libopenal.so: unknown type
		liblwjgl_tinyfd.so: unknown type
		liblwjgl_opengl.so: unknown type
		liblwjgl_vma.so: unknown type
		libjemalloc.so: unknown type
		liblwjgl.so: unknown type
	LWJGL platform: LINUX
	LWJGL architecture: X64
Stacktrace:
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201)
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105)
	at net.minecraft.client.main.Main.main(Main.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
-- LWJGL debug log --
Details:
	Log: 
Stacktrace:
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201)
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105)
	at net.minecraft.client.main.Main.main(Main.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
-- Libraries loaded --
Details:
	Loading order: vma,OpenGL,tinyfd,OpenAL,freetype,SDL,shaderc,STB,spvc
	Loading index: 5
Stacktrace:
	at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105)
	at net.minecraft.client.main.Main.main(Main.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
-- System Details --
Details:`

**Comment by Kaydax** [comment]
> I tested using the AppImage version because the Flatpak Minecraft snapshot instance `26-3-snapshot-4` throws this error:
> 
> ## `[10:08:56] [main/WARN]: Failed to get system info for SDL Platform
> java.lang.NoClassDefFoundError: org/lwjgl/sdl/SDLPlatform
> at com.mojang.blaze3d.platform.Window.getPlatform(Window.java:126)
> at net.minecraft.SystemReport.setDetail(SystemReport.java:96)
> at net.minecraft.client.Minecraft.fillSystemReport(Minecraft.java:2570)
> at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2522)
> at net.minecraft.client.main.Main.main(Main.java:147)
> at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> at java.base/java.lang.reflect.Method.invoke(Method.java:565)
> at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
> at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
> at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
> at org.polymc.EntryPoint.listen(EntryPoint.java:144)
> at org.polymc.EntryPoint.main(EntryPoint.java:74)
> Caused by: java.lang.ClassNotFoundException: org.lwjgl.sdl.SDLPlatform
> at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
> ... 12 more
> ---- Minecraft Crash Report ----
> // Surprise! Haha. Well, this is awkward.
> Time: 2026-07-24 10:08:56
> Description: Loading library SDL
> java.lang.NoClassDefFoundError: org/lwjgl/sdl/SDL
> at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadSdl(NativeLibrariesBootstrap.java:284)
> at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201)
> at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105)
> at net.minecraft.client.main.Main.main(Main.java:142)
> at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> at java.base/java.lang.reflect.Method.invoke(Method.java:565)
> at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
> at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
> at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
> at org.polymc.EntryPoint.listen(EntryPoint.java:144)
> at org.polymc.EntryPoint.main(EntryPoint.java:74)
> Caused by: java.lang.ClassNotFoundException: org.lwjgl.sdl.SDL
> at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
> ... 11 more
> A detailed walkthrough of the error, its code path and all known details is as follows:
> -- Head -- Thread: main Stacktrace: at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadSdl(NativeLibrariesBootstrap.java:284) at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201) at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105) -- Library directory contents -- Details: Contents of java.library.path : Contents of org.lwjgl.librarypath: libfreetype.so: unknown type libopenal.so: unknown type liblwjgl_tinyfd.so: unknown type liblwjgl_opengl.so: unknown type liblwjgl_vma.so: unknown type libjemalloc.so: unknown type liblwjgl.so: unknown type LWJGL platform: LINUX LWJGL architecture: X64 Stacktrace: at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201) at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105) at net.minecraft.client.main.Main.main(Main.java:142) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:565) at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) at org.polymc.EntryPoint.listen(EntryPoint.java:144) at org.polymc.EntryPoint.main(EntryPoint.java:74) -- LWJGL debug log -- Details: Log: Stacktrace: at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201) at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105) at net.minecraft.client.main.Main.main(Main.java:142) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:565) at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) at org.polymc.EntryPoint.listen(EntryPoint.java:144) at org.polymc.EntryPoint.main(EntryPoint.java:74) -- Libraries loaded -- Details: Loading order: vma,OpenGL,tinyfd,OpenAL,freetype,SDL,shaderc,STB,spvc Loading index: 5 Stacktrace: at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105) at net.minecraft.client.main.Main.main(Main.java:142) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:565) at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) at org.polymc.EntryPoint.listen(EntryPoint.java:144) at org.polymc.EntryPoint.main(EntryPoint.java:74) -- Initialization -- Details: Modules: Stacktrace: at net.minecraft.client.main.Main.main(Main.java:142) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:565) at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) at org.polymc.EntryPoint.listen(EntryPoint.java:144) at org.polymc.EntryPoint.main(EntryPoint.java:74) -- System Details -- Details:`

The SDL error seems to me like your metadata is out of date and you still have the old broken lwjgl. Try deleting the `meta`, `libraries` and `cache` folders in `~/.local/share/PolyMC` and try again without any launch arguments. Else it's some stupid bullshit with GNOME because mutter is held together with duct tape and glue

**Comment by outusuke** [comment]
> > I tested using the AppImage version because the Flatpak Minecraft snapshot instance `26-3-snapshot-4` throws this error:
> > ## `[10:08:56] [main/WARN]: Failed to get system info for SDL Platform
> > java.lang.NoClassDefFoundError: org/lwjgl/sdl/SDLPlatform
> > at com.mojang.blaze3d.platform.Window.getPlatform(Window.java:126)
> > at net.minecraft.SystemReport.setDetail(SystemReport.java:96)
> > at net.minecraft.client.Minecraft.fillSystemReport(Minecraft.java:2570)
> > at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2522)
> > at net.minecraft.client.main.Main.main(Main.java:147)
> > at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> > at java.base/java.lang.reflect.Method.invoke(Method.java:565)
> > at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
> > at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
> > at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
> > at org.polymc.EntryPoint.listen(EntryPoint.java:144)
> > at org.polymc.EntryPoint.main(EntryPoint.java:74)
> > Caused by: java.lang.ClassNotFoundException: org.lwjgl.sdl.SDLPlatform
> > at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
> > at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
> > ... 12 more
> > ---- Minecraft Crash Report ----
> > // Surprise! Haha. Well, this is awkward.
> > Time: 2026-07-24 10:08:56
> > Description: Loading library SDL
> > java.lang.NoClassDefFoundError: org/lwjgl/sdl/SDL
> > at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadSdl(NativeLibrariesBootstrap.java:284)
> > at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201)
> > at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105)
> > at net.minecraft.client.main.Main.main(Main.java:142)
> > at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> > at java.base/java.lang.reflect.Method.invoke(Method.java:565)
> > at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
> > at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
> > at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
> > at org.polymc.EntryPoint.listen(EntryPoint.java:144)
> > at org.polymc.EntryPoint.main(EntryPoint.java:74)
> > Caused by: java.lang.ClassNotFoundException: org.lwjgl.sdl.SDL
> > at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
> > at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
> > ... 11 more
> > A detailed walkthrough of the error, its code path and all known details is as follows:
> > -- Head -- Thread: main Stacktrace: at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadSdl(NativeLibrariesBootstrap.java:284) at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201) at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105) -- Library directory contents -- Details: Contents of java.library.path : Contents of org.lwjgl.librarypath: libfreetype.so: unknown type libopenal.so: unknown type liblwjgl_tinyfd.so: unknown type liblwjgl_opengl.so: unknown type liblwjgl_vma.so: unknown type libjemalloc.so: unknown type liblwjgl.so: unknown type LWJGL platform: LINUX LWJGL architecture: X64 Stacktrace: at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201) at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105) at net.minecraft.client.main.Main.main(Main.java:142) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:565) at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) at org.polymc.EntryPoint.listen(EntryPoint.java:144) at org.polymc.EntryPoint.main(EntryPoint.java:74) -- LWJGL debug log -- Details: Log: Stacktrace: at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibrary(NativeLibrariesBootstrap.java:201) at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105) at net.minecraft.client.main.Main.main(Main.java:142) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:565) at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) at org.polymc.EntryPoint.listen(EntryPoint.java:144) at org.polymc.EntryPoint.main(EntryPoint.java:74) -- Libraries loaded -- Details: Loading order: vma,OpenGL,tinyfd,OpenAL,freetype,SDL,shaderc,STB,spvc Loading index: 5 Stacktrace: at com.mojang.blaze3d.platform.NativeLibrariesBootstrap.loadLibraries(NativeLibrariesBootstrap.java:105) at net.minecraft.client.main.Main.main(Main.java:142) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:565) at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) at org.polymc.EntryPoint.listen(EntryPoint.java:144) at org.polymc.EntryPoint.main(EntryPoint.java:74) -- Initialization -- Details: Modules: Stacktrace: at net.minecraft.client.main.Main.main(Main.java:142) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:565) at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) at org.polymc.EntryPoint.listen(EntryPoint.java:144) at org.polymc.EntryPoint.main(EntryPoint.java:74) -- System Details -- Details:`
> 
> The SDL error seems to me like your metadata is out of date and you still have the old broken lwjgl. Try deleting the `meta`, `libraries` and `cache` folders in `~/.local/share/PolyMC` and try again without any launch arguments. Else it's some stupid bullshit with GNOME because mutter is held together with duct tape and glue

The AppImage works, but the Flatpak version `26-3-snapshot-4` still throws this error even after deleting those folders.

It’s not a big problem for now since I’m only using the snapshot for testing.

**Comment by Kaydax** [comment]
@outusuke the flatpak version is out of date currently and should not be used. Please use the AppImage or compile from source
