### PR TITLE
Allow locked Mojang accounts to (mostly) work

### LINKED ISSUE #427: Enable Offline Access to Unmigrated Accounts
### Role

I'm a Minecraft player with an unmigrated account.

### Suggestion

Enable the ability to use offline mode if the user's account is valid but unmigrated.

### Benefit

To keep some semblance of access to the game I paid for.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Users have lost access to their ability to play due to the Microsoft acquisition and subsequent modification of the login system, there's nothing PolyMC can do about that. 

However, I propose enabling the offline account system if the user's account reports "Minecraft Java profile acquisition failed." on login. This is a different error code than an invalid username/password combination and can be used to infer a legitimate Minecraft purchase.

https://github.com/PolyMC/PolyMC/issues/422

### PR DESCRIPTION
**Pull request by TheCodex6824**
Closes #427 

This PR changes the Mojang login flow to bypass Mojang locking these accounts. Specifically, the profile endpoint (https://api.minecraftservices.com/minecraft/profile and similar) returns HTTP 403 codes for these locked accounts, which makes the launcher think that logging in failed. Most of the information from there can be found from other sources, so switching to those allows Mojang users to log in again.

This does not bypass authentication or enable piracy in any way - in fact, users will be able to play on premium servers again with this change.

Also, to prevent some of the workarounds I had to include from possibly affecting MS users, this PR only changes the login flow for Mojang users. Microsoft accounts use the same profile endpoint as before.

From my own testing, this enables my unmigrated account to launch the game and join premium servers. Sadly, it appears that we are **unable** to change skins, as that seems to also be blocked by Mojang. Capes are probably similarly blocked, although I do not have any so I was not able to test it.

### CODE REVIEW

**Comment by DioEgizio** [comment]
This doesn't build on Qt 5.12

**Comment by DioEgizio** [comment]
From the CI:

FAILED: launcher/CMakeFiles/Launcher_logic.dir/minecraft/auth/Parsers.cpp.o 
/usr/bin/c++ -DLAUNCHER_JARS_LOCATION=share/jars -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DQUAZIP_STATIC -I/home/runner/work/PolyMC/PolyMC/build/launcher -I/home/runner/work/PolyMC/PolyMC/launcher -I/home/runner/work/PolyMC/PolyMC/build/launcher/Launcher_logic_autogen/include -I/home/runner/work/PolyMC/PolyMC/libraries/systeminfo/include -I/home/runner/work/PolyMC/PolyMC/libraries/classparser/include -I/home/runner/work/PolyMC/PolyMC/libraries/quazip -I/home/runner/work/PolyMC/PolyMC/libraries/quazip/quazip -I/home/runner/work/PolyMC/PolyMC/libraries/libnbtplusplus/include -I/home/runner/work/PolyMC/PolyMC/build/libraries/libnbtplusplus -I/home/runner/work/PolyMC/PolyMC/libraries/optional-bare/include -I/home/runner/work/PolyMC/PolyMC/libraries/tomlc99/include -I/home/runner/work/PolyMC/PolyMC/buildconfig -I/home/runner/work/PolyMC/PolyMC/libraries/katabasis/include -I/home/runner/work/PolyMC/PolyMC/libraries/iconfix -I/home/runner/work/PolyMC/PolyMC/build/libraries/iconfix -I/home/runner/work/PolyMC/PolyMC/libraries/hoedown/include -I/home/runner/work/PolyMC/PolyMC/libraries/LocalPeer/include -I/home/runner/work/PolyMC/PolyMC/libraries/rainbow/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -Wall -pedantic -Werror -Wno-deprecated-declarations -D_GLIBCXX_USE_CXX11_ABI=0 -fstack-protector-strong --param=ssp-buffer-size=4 -O3 -D_FORTIFY_SOURCE=2  -DQT_NO_DEPRECATED_WARNINGS=Y -g -Werror=return-type -fPIC -fPIC -std=gnu++11 -MD -MT launcher/CMakeFiles/Launcher_logic.dir/minecraft/auth/Parsers.cpp.o -MF launcher/CMakeFiles/Launcher_logic.dir/minecraft/auth/Parsers.cpp.o.d -o launcher/CMakeFiles/Launcher_logic.dir/minecraft/auth/Parsers.cpp.o -c /home/runner/work/PolyMC/PolyMC/launcher/minecraft/auth/Parsers.cpp
/home/runner/work/PolyMC/PolyMC/launcher/minecraft/auth/Parsers.cpp: In function ‘bool Parsers::parseMinecraftProfileMojang(QByteArray&, MinecraftProfile&)’:
/home/runner/work/PolyMC/PolyMC/launcher/minecraft/auth/Parsers.cpp:310:92: error: ‘AbortOnBase64DecodingErrors’ is not a member of ‘QByteArray’
  310 |             texturePayload = QByteArray::fromBase64(value.toString().toUtf8(), QByteArray::AbortOnBase64DecodingErrors);
      |                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by TheCodex6824** [comment]
> This doesn't build on Qt 5.12

Sorry about that, that's what I get for seeing "this enum was introduced in Qt 5.2" and then missing "this enum **value** was added in Qt 5.15".

**Comment by txtsd** [comment]
You can do a Qt version check and still have it in the code so users with newer Qt can take advantage of it.

**Review by txtsd — APPROVED** [review]

**Review by d-513 — APPROVED** [review]
why did I migrate.....

**Comment by DioEgizio** [comment]
Because Microsoft is Microsoft

**Comment by TheCodex6824** [comment]
> Because Microsoft is Microsoft

From an infuriating exchange I had with Mojang support, Mojang is at least part of the problem. They seem to be aware that people are losing accounts because they can't / won't migrate, but rather than work with them, their strategy seems to be to strongarm everyone into an MS account. From there, when the inevitable issues happen (like the account getting locked for "suspicious activity" and requiring a phone number that isn't on MS's magic phone blocklist) they just say "sorry, we can't help with MS accounts, go to MS instead".

**Review by Jookly123 — APPROVED** [review]

**Comment by d-513** [comment]
Mojang is basically MS at this point in terms of quality. Everything is janky and they don't care if someone loses their account

**Comment by Scrumplex** [comment]
I assume this fixes #427?

File: launcher/minecraft/auth/Parsers.cpp [hunk 1]
```diff
@@ -212,6 +212,180 @@ bool parseMinecraftProfile(QByteArray & data, MinecraftProfile &output) {
...
+#endif
+
+    QJsonParseError jsonError;
+    QJsonDocument doc = QJsonDocument::fromJson(data, &jsonError);
+    if(jsonError.error) {
+        qWarning() << "Failed to parse response as JSON: " << jsonError.errorString();
+        return false;
+    }
+
+    auto obj = doc.object();
```
Comment (Scrumplex) [inline launcher/minecraft/auth/Parsers.cpp]: include our `Json.h` and:
```suggestion
    auto obj = Json::requireObject(doc, "mojang minecraft profile");
```

File: launcher/minecraft/auth/Parsers.cpp [hunk 2]
```diff
@@ -212,6 +212,180 @@ bool parseMinecraftProfile(QByteArray & data, MinecraftProfile &output) {
...
+        return false;
+    }
+
+    doc = QJsonDocument::fromJson(texturePayload, &jsonError);
+    if(jsonError.error) {
+        qWarning() << "Failed to parse response as JSON: " << jsonError.errorString();
+        return false;
+    }
+
+    obj = doc.object();
```
Comment (Scrumplex) [inline launcher/minecraft/auth/Parsers.cpp]:
```suggestion
    obj = Json::requireObject(doc, "texture payload");
```

**Review by Scrumplex — APPROVED** [review]
LGTM. I am not confident that this will work for a long time, but might as well have it in the launcher while it's possible

**Comment by TheCodex6824** [comment]
> I assume this fixes #427?

I guess it does, at least for now. Like you, I doubt this will last forever, but it's better than just giving up. I'll also get to your feedback when I get home in a few hours.

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
Thanks!

**Comment by afeuerstein** [comment]
Fuck. I just migrated. Instant regret.

**Comment by Scrumplex** [comment]
RIP. It was fun for the time it lasted
